version: "3"


services:

  ecommerce_api:
    build: .
    image: ecommerce_api
    container_name: ecommerce_api
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py loaddata users.json &&
      python manage.py runserver 0.0.0.0:8000"